### ISSUE TITLE
[PE-D][Tester A] Long role title causes truncation of font

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T13-3/tp#202]
Issued the command `add-app r/Summer Software Engineering Internship and Site Reliability Intern c/Google e/fast_hires@graggle.com s/applied` and the title got cut off

![image.png](https://raw.githubusercontent.com/ExtraShotLatte/ped/main/files/dd00794a-1435-4194-8caa-eb08a2225c23.png)

Maybe word warping would help?

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ExtraShotLatte/ped#5

**Comment by XylusChen** [comment]
Duplicate Issue. #186
