### ISSUE TITLE
[PE-D][Tester B] List disappears when sort by deadline when deadline doesn't exist 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T13-3/tp#213]
![image.png](https://raw.githubusercontent.com/HJ-PRK/ped/main/files/5b66f24b-a5b2-4f1f-9963-8c5aae5c86f3.png)

When sort the list by deadline when none of the applications has a deadline, it does not show any applications.
It is expected to show an error message when a deadline doesn't exist on the list.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: HJ-PRK/ped#7

**Comment by noahxinjie** [comment]
Not resolved as this is a feature flaw
